name: matt_gleich_github_io
description: Matthew Gleich's Personal website
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.1
  material_design_icons_flutter: ^3.4.4895
  simple_animations: ^1.3.6
  flutter_staggered_animations: ^0.1.2
  provider: ">=4.0.0 <5.0.0"
  responsive_builder: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel/Abel-Regular.ttf
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow/Tomorrow-Regular.ttf
        - asset: assets/fonts/Tomorrow/Tomorrow-Italic.ttf
          style: italic
        - asset: assets/fonts/Tomorrow/Tomorrow-Bold.ttf
          weight: 700
