name: matt_gleich_github_io
description: My personal website
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.1
  material_design_icons_flutter: ^3.4.4895
  simple_animations: ^1.3.6
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
