name: matt_gleich_github_io
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^3.1.0
  url_launcher: ^5.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Public Sans
      fonts:
        - asset: fonts/Public-Sans/Public-Sans-100.ttf
        - asset: fonts/Public-Sans/Public-Sans-100italic.tff
        - asset: fonts/Public-Sans/Public-Sans-200.tff
        - asset: fonts/Public-Sans/Public-Sans-200italic.tff
        - asset: fonts/Public-Sans/Public-Sans-300.tff
        - asset: fonts/Public-Sans/Public-Sans-300italic.tff
        - asset: fonts/Public-Sans/Public-Sans-400.tff
        - asset: fonts/Public-Sans/Public-Sans-400italic.tff
        - asset: fonts/Public-Sans/Public-Sans-500.tff
        - asset: fonts/Public-Sans/Public-Sans-500italic.tff
        - asset: fonts/Public-Sans/Public-Sans-600.tff
        - asset: fonts/Public-Sans/Public-Sans-600italic.tff
        - asset: fonts/Public-Sans/Public-Sans-700.tff
        - asset: fonts/Public-Sans/Public-Sans-700italic.tff
        - asset: fonts/Public-Sans/Public-Sans-800.tff
        - asset: fonts/Public-Sans/Public-Sans-800italic.tff
        - asset: fonts/Public-Sans/Public-Sans-900.tff
        - asset: fonts/Public-Sans/Public-Sans-900italic.tff
        - asset: fonts/Public-Sans/Public-Sans-italic.tff
        - asset: fonts/Public-Sans/Public-Sans-regular.tff
