description: "Matthew Gleich's Personal website"
name: 'personal_site'
version: '1.0.0+1'
dependencies:
  animated_text_kit: '^2.0.0'
  flutter_staggered_animations: '^0.1.2'
  material_design_icons_flutter: '^3.4.4895'
  provider: '>=4.0.0 <5.0.0'
  responsive_builder: '^0.1.2'
  url_launcher: '^5.4.1'
  flutter:
    sdk: flutter
  flutter_markdown: ^0.4.1
dev_dependencies:
  import_sorter: '^3.0.6'
  local_google_fonts: '^1.0.8'
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.7.0 <3.0.0'
flutter:
  assets:
    - 'assets/images/'
    - 'assets/markdown/'
  fonts:
    - family: 'Abel'
      fonts:
        - asset: 'assets/fonts/googleFonts/Abel/Abel-400.ttf'
          weight: 400
    - family: 'Tomorrow'
      fonts:
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-400.ttf'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-400i.ttf'
          style: 'italic'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Tomorrow/Tomorrow-700.ttf'
          weight: 700
    - family: 'Computer Modern'
      fonts:
        - asset: 'assets/fonts/computer-modern/cmunti.ttf'
          style: 'italic'
  uses-material-design: true
google_fonts:
  docs: false
  fonts:
    - 'Abel'
    - Tomorrow:
        - 400
        - '400i'
        - 700
import_sorter:
  emojis: true
