name: Flutter Build
on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.14.x"
          channel: "beta"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
