name: Format

on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run format
        run: dartfmt --dry-run --set-exit-if-changed .
