name: Publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.14.x"
          channel: "beta"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - name: Publish
        run: |
          git config --global user.email "${{ secrets.email }}"
          git config --global user.name "Publishing Bot"
          git remote add origin https://Matt-Gleich:${{ secrets.ghToken }}@github.com/Matt-Gleich/Personal-Site.git
          sh publish.sh
